AsyncAwait/AsyncAwaitThirdMVC/Models/Downloader.cs
using System;
using System.Collections.Concurrent;
using System.Net;
using System.Threading.Tasks;

namespace AsyncAwaitThirdMVC.Models
{
    public class Downloader
    {
        private static readonly ConcurrentDictionary<Guid, TaskModel> DownloaderManager
            = new ConcurrentDictionary<Guid, TaskModel>();

        public static void CreateNew(UrlModel model)
        {
            model.Id = Guid.NewGuid();
            var taskmodel = new TaskModel(model);
            taskmodel.Client = new WebClient();
            
            DownloaderManager.TryAdd(model.Id, taskmodel);
        }

        public static async Task<string> StartNew(Guid id)
        {
            TaskModel taskmodel;
            DownloaderManager.TryRemove(id, out taskmodel);
            var client = taskmodel.Client;
            var uri = new Uri(taskmodel.Site);
            taskmodel = null;
            return await client.DownloadStringTaskAsync(uri);
        }

        public static UrlModel Cancel(UrlModel model)
        {
            TaskModel taskmodel;
            DownloaderManager.TryGetValue(model.Id, out taskmodel);
            if (taskmodel?.Client != null)
                taskmodel.Client.CancelAsync();
            model.Content = "Canceled";

            return model;
        }
    }
}

AsyncAwait/AsyncAwaitThirdMVC/Models/TaskModel.cs
using System;
using System.Net;

namespace AsyncAwaitThirdMVC.Models
{
    public class TaskModel
    {
        public string Site { get; set; }
        public Guid Id { get; set; }
        public WebClient Client { get; set; }
        public TaskModel(UrlModel model)
        {
            Site = model.Site;
            Id = model.Id;
        }
    }
}

AsyncAwait/AsyncAwaitThirdMVC/Models/UrlModel.cs
using System;

namespace AsyncAwaitThirdMVC.Models
{
    public class UrlModel
    {
        public string Site { get; set; }
        public Guid Id { get; set; }
        public string Content { get; set; }
    }
}

AsyncAwait/AsyncAwaitThirdMVC/Controllers/HomeController.cs
using System.Web.Mvc;

namespace AsyncAwaitThirdMVC.Controllers
{
    public class HomeController : Controller
    {
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }     
    }
}

AsyncAwait/AsyncAwaitThirdMVC/Controllers/LoadingController.cs
//description
/*
 *Напишите простейший менеджер закачек. Пользователь задает адрес страницы, которую необходимо загрузить.
 * В процессе загрузки пользователь может ее отменить. 
 * Пользователь может задавать несколько источников для закачки. todo: this is not implemented
 * Скачивание страниц не должно блокировать интерфейс приложения.
 */

using System;
using System.Threading.Tasks;
using System.Web.Mvc;
using AsyncAwaitThirdMVC.Models;

namespace AsyncAwaitThirdMVC.Controllers
{
    public class LoadingController : Controller
    {
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        } // todo: please, use some common code style here
        [HttpPost]
        public ActionResult DownloadSite(UrlModel model)
        {
            Downloader.CreateNew(model);

            return PartialView(model);
        }
        public ActionResult Cancel(UrlModel model)
        {
            return PartialView(Downloader.Cancel(model));
        }

        public async Task<string> StartDownload(Guid id)
        {
            return await Downloader.StartNew(id);
        }
    }
}

AsyncAwait/AsyncAwaitThirdMVC/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

AsyncAwait/AsyncAwaitThirdMVC/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

AsyncAwait/AsyncAwaitThirdMVC/Views/Home/Index.cshtml
<td> Bonjorno </td>

AsyncAwait/AsyncAwaitThirdMVC/Views/Loading/Cancel.cshtml
@model AsyncAwaitThirdMVC.Models.UrlModel
@Html.DisplayFor(model => model.Content) 

AsyncAwait/AsyncAwaitThirdMVC/Views/Loading/DownloadSite.cshtml
@model AsyncAwaitThirdMVC.Models.UrlModel

@{
    AjaxOptions ajaxOpts = new AjaxOptions
    {
        InsertionMode = InsertionMode.ReplaceWith,
        UpdateTargetId = Model.Id.ToString()
    };
}
<div id="@Model.Id.ToString()" class="col-md-4">
    <h4>UrlState</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Site)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Site)
        </dd>
    </dl>
    <div>
        качаем       
    </div>
    <p>
        <iframe src="@Url.Action("StartDownload", "Loading", new { Id = Model.Id })"></iframe>

        @using (Ajax.BeginForm("Cancel", "Loading", ajaxOpts))
        { 
            @Html.HiddenFor(model => model.Id)
            <input type="submit" value="Cancel" class="btn btn-default" />
        }
    </p>
</div>

AsyncAwait/AsyncAwaitThirdMVC/Views/Loading/Index.cshtml
@model AsyncAwaitThirdMVC.Models.UrlModel

@{
    ViewBag.Title = "Home Page";
    AjaxOptions ajaxOpts = new AjaxOptions
    {
        InsertionMode = InsertionMode.InsertAfter,
        UpdateTargetId = "list",
        LoadingElementId = "loading",
        LoadingElementDuration = 1000,
    };
}

<div class="jumbotron">
    <h1>Enter site</h1>
    <h1>К примеру  https://google.com</h1>
    @using (Ajax.BeginForm("DownloadSite", "Loading", ajaxOpts))
    {
        @Html.LabelFor(model => model.Site)
        @Html.EditorFor(model => model.Site)
        <input type="submit" value="Save" class="btn btn-default" />
 
    }
</div>
<div class="row" id="list">

</div>

<div id="loading" class="load" style="display: none">
    <p>Loading Data...</p>
</div>

AsyncAwait/AsyncAwaitThirdMVC/Views/Loading/StartDownload.cshtml
@model AsyncAwaitThirdMVC.Models.UrlModel

<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Site)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Site)
        </dd>
        <dd>
            @Html.DisplayFor(model => model.Id)
        </dd>
    </dl>

</div>

AsyncAwait/AsyncAwaitThirdMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("LoadManager","Index","Loading")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>